name: mnist_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pandas
  - pillow
  - bokeh
  - pytorch
  - torchvision
  - tqdm
  - ipywidgets
  - jupyter
  - streamlit
  - pip
  - pip:
      - streamlit-drawable-canvas
      - livelossplot
